version: "3"

services:
  website:
    container_name: website
    build:
      context: .
      dockerfile: ./apps/website/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  blog:
    container_name: blog
    build:
      context: .
      dockerfile: ./apps/blog/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true