services:
  app:
    build:
      context: ..  # Specifies the build context (parent directory)
      dockerfile: .devcontainer/Dockerfile  # Path to the Dockerfile in the .devcontainer directory
    container_name: stunning-braccoli
    image: stunning-braccoli-sites
    volumes:
      - stunning-braccoli-volume:/workspace  # Mounts the volume to /workspace
    ports:
      - "3000:3000"  # Maps port 3000
      - "3001:3001"  # Maps port 3001

volumes:
  stunning-braccoli-volume:  # Defines the volume
